language: go
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
env:
  - GOARCH=amd64
  - GOARCH=386
sudo: false
before_install:
  - go get github.com/mattn/goveralls
script:
  - wget -O dep https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64
  - chmod +x dep
  - ./dep ensure
  - ./test.sh
  - ./coverage.sh --coveralls
notifications:
  email: false
