language: go
go:
  - 1.0.3
  - 1.1.2
env:
  - GOARCH=amd64
  - GOARCH=386
install:
  - go get github.com/kr/godep || true
  # these need to be installed manually for go1.0.x
  - go get github.com/bitly/go-nsq
  - go get github.com/bitly/go-simplejson
  - go get github.com/bitly/go-hostpool
  - go get github.com/mreiferson/go-snappystream
  - go get github.com/bmizerany/assert
script:
  - export PATH="$HOME/gopath/bin:$PATH"
  - ./test.sh
notifications:
  email: false
