language: go
go:
  - 1.6.x
  - 1.7.x
env:
  - GOARCH=amd64
  - GOARCH=386
sudo: false
script:
  - curl -s https://raw.githubusercontent.com/pote/gpm/v1.4.0/bin/gpm > gpm
  - chmod +x gpm
  - ./gpm install
  - ./test.sh
notifications:
  email: false
